Description:  This template configuration for the workgroup for the Amazon Athena Tutorial. 

Parameters:
  S3LocationAthenaResults: 
    Description: S3 location for the Athena results to be stored. 
    Type: String 

Resources:
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: DataEngineeringCourseAthenaWorkgroup
      Description: The workgroup for the data engeering course. 
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation:
            Ref: S3LocationAthenaResults